---
- name: reload oauthproxy
  systemd:
    name: oauth2-proxy@{{ oauthproxy_name }}
    state: reloaded
    daemon_reload: yes

- name: restart oauthproxy
  systemd:
    name: oauth2-proxy@{{ oauthproxy_name }}
    state: restarted
    daemon_reload: yes
